### ISSUE TITLE
undoActivate from HasActiveFlag not working

### ISSUE THREAD

**Issue by rayronvictor** [cybercog/laravel-eloquent-flag#61]
`$this->save()` shouldn't be after `$this->setAttribute('is_active', false);`? 

https://github.com/cybercog/laravel-eloquent-flag/blob/504bbd7e16d33c0eed12441cec51f3e92d8a50a1/src/Traits/Classic/HasActiveFlagHelpers.php#L41-L47

**Comment by antonkomarev** [comment]
[v5.1.1](https://github.com/cybercog/laravel-eloquent-flag/releases/tag/5.1.1) has been released.

Now I see that tests are written incorrectly. We are not taking fresh records before assertions.
