### ISSUE TITLE
support laravel 7

### ISSUE THREAD

**Issue by maherelgamil** [cybercog/laravel-eloquent-flag#64]
please add support for laravel 7.0

**Comment by antonkomarev** [comment]
Plan to start adding this support on this weekend. Feel free to add PR if you want to see it earlier.

**Comment by antonkomarev** [comment]
Laravel 7.x support was added in [Laravel Eloquent Flag v5.1.2 release](https://github.com/cybercog/laravel-eloquent-flag/releases/tag/5.1.2)
